external_components:
  - source:
      type: git
      url: https://github.com/muxa/esphome-state-machine

state_machine:
  - name: Fan Mode
    states:
    - "NORMAL"
    - "SILENCED"
    # TODO: Boost mode? 
    initial_state: NORMAL
    inputs:
      - name: TOGGLE
        transitions:
          - NORMAL -> SILENCED
          - SILENCED -> NORMAL

text_sensor:
  - platform: state_machine
    name: Cooling Mode