binary_sensor:
  - platform: template
    device_class: safety #or problem
    id: error_handler
    name: "Error Handler"
    lambda: |-
      float ntc_temp = id(ntc_sensor).state;
      bool is_error = false;
      if ( ntc_temp < 10 ) {
        is_error = true;
      }
      if ( ntc_temp > 260 ) {
        is_error = true;
      }
      if (is_error) {
        if (id(state_machine_mode).current_state() != "ERROR") {
          id(state_machine_mode).transition("ERROR_ENTER");
        }
      } else {
        if (id(state_machine_mode).current_state() == "ERROR") {
          if (id(previous_state) == "NORMAL") {
            id(state_machine_mode).transition("ERROR2NORMAL");
          } else if (id(previous_state) == "SILENCED") {
            id(state_machine_mode).transition("ERROR2SILENCED");
          }
        }
      }
      return is_error;
