# Read the temperature from a NTC thermistor
# https://esphome.io/components/sensor/ntc.html
# https://docs.espressif.com/projects/esp-idf/en/v4.4.1/esp32s2/api-reference/peripherals/adc.html
# https://learn.adafruit.com/thermistor/using-a-thermistor#self-heating-3-22

#TODO: reduce the logging level
sensor:
  - platform: ntc
    name: Thermsistor Temperature
    sensor: resistance_sensor
    calibration:
      - 400kOhm -> 0°C
      - 93kOhm -> 21°C
      - 3kOhm -> 152°C 

  # https://esphome.io/components/sensor/resistance.html
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: ${ntc_resistance} #For best results have a +/- 1% resistor
    name: Thermsistor Resistance
    unit_of_measurement: 'Ω'
    accuracy_decimals: 0
    # filters:
    #   - multiply: 0.001 #This is the problem it fixes the gui, but breaks the maths

  - platform: adc
    id: source_sensor
    pin: 5
    update_interval: 2s
    # https://docs.espressif.com/projects/esp-idf/en/v4.4.1/esp32s2/api-reference/peripherals/adc.html
    # https://esphome.io/components/sensor/adc.html#esp32-attenuation
    attenuation: 11db
    on_value:
      then:
        - component.update: analog_value

  - platform: template
    name: "Thermsistor Voltage"
    id: analog_value
    unit_of_measurement: "V"
    update_interval: 2s
    accuracy_decimals: 3
    lambda: |- 
      auto adc_fraction = id(source_sensor).state;
      return adc_fraction;
