# Voltage sensor uses a PC817 OctoCoupler connected in series to the hotend heating element.
# It detects 24v (~7hz) PWM signal
# If detected, it means the hotend is heating up

binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP # set the mode to INPUT_PULLUP or INPUT_PULLDOWN depending on your wiring
    name: "Heater"
    filters:
      - invert:
