wifi: 
  output_power: 10 # https://github.com/esphome/issues/issues/3988#issuecomment-1449954758
  ap:
    ssid: "AnkerMake M5 Muffler"
  reboot_timeout: 0s
  power_save_mode: none

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s